### ISSUE TITLE
PlotFunctionMonitor won't work in notebooks

### ISSUE THREAD

**Issue by JoyMonteiro** [mcgibbon/sympl#3]
PlotFunctionMonitor does not work in jupyter notebooks since apparently `plt.pause` does not work within notebooks. Not really sure how this can be addressed!

**Comment by mcgibbon** [comment]
I'm not sure whether it's possible to have dynamically updating plots in-line in the IPython notebook. Does it work if you initialize the PlotFunctionMonitor with interactive=False? This will still call plt.pause. If it doesn't work, we can add logic so that plt.pause is only called when interactive=True.

**Comment by mcgibbon** [comment]
It's also possible that replacing plt.pause with time.sleep will be sufficient.

**Comment by JoyMonteiro** [comment]
Yes, the interactive plots in the older climt worked when I used time.sleep(). plt.pause() does not seem to have been implemented for interactive backends.

Should I try it out and submit a PR?

**Comment by mcgibbon** [comment]
I've pushed a change that may fix the problem. Try pulling it and see if that works, if not a PR would be great.

**Comment by JoyMonteiro** [comment]
Sorry for the delay, was caught up in some work that needed to get done asap.

No, the changes did not fix the problem. It seems as if plt.draw_all() is the issue.
if I use self._fig.canvas.draw(), with works without any time.sleep() calls, both on the cmd line
and in notebooks.

**Comment by mcgibbon** [comment]
Fixed by #4 .
